name: movie_roulette
description: "Movie Roulette: Skip the Scrolling, Start Watching!"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
