name: movie_roulette
description: "Movie Roulette: Skip the Scrolling, Start Watching!"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.8
  http: ^1.2.2
  roulette: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/